services:
  - type: web
    name: copperinu-backend
    env: python
    rootDir: backend
    buildCommand: "pip install gunicorn && pip install -r requirements.txt"
    startCommand: "gunicorn main:app -b 0.0.0.0:$PORT"